// Writes src/catalog.ts from the message catalogues of the Raoh Specification checkout given.
//
//     node scripts/catalog.ts <raoh-specification checkout>
//
// The catalogues are the specification's and are carried as their text, word for word, so that
// what this library ships is what the messages-en and messages-ja profiles hold it to. The commit
// they were read at goes into the file.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const spec = process.argv[2];
if (spec === undefined) {
  console.error("usage: node scripts/catalog.ts <raoh-specification checkout>");
  process.exit(2);
}
const commit = execFileSync("git", ["-C", spec, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
const text = (locale: string) => readFileSync(join(spec, "catalog", "messages", `${locale}.properties`), "utf8");

const out = [
  "// Generated by scripts/catalog.ts from the message catalogues of the Raoh Specification at",
  `// ${commit}. Do not edit: regenerate it instead.`,
  "",
  "/** Each locale's catalogue, as the text of its `.properties` file. */",
  "export const CATALOG = {",
  `  en: ${JSON.stringify(text("en"))},`,
  `  ja: ${JSON.stringify(text("ja"))},`,
  "} as const;",
  "",
];
writeFileSync(new URL("../src/catalog.ts", import.meta.url), out.join("\n"));
